"""add gross_margin to items

Revision ID: 721224e62c28
Revises: 
Create Date: 2025-01-02 20:01:13.426892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721224e62c28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_margin', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('gross_margin')

    # ### end Alembic commands ###
