"""Add unit of measure fields to Item

Revision ID: 74b9520e4162
Revises: 
Create Date: 2024-12-26 13:22:35.449864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b9520e4162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_unit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('stock_unit', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('stock_unit')
        batch_op.drop_column('price_unit')

    # ### end Alembic commands ###
